# Generated by Django 5.2.3 on 2025-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnesslog',
            name='mood',
            field=models.CharField(blank=True, choices=[('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad')], max_length=50),
        ),
    ]
