# Generated by Django 5.2.3 on 2025-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApp', '0002_alter_wellnesslog_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_hour',
            field=models.TimeField(default='09:00'),
        ),
    ]
