# Generated by Django 5.2.3 on 2025-07-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApp', '0004_userprofile_full_name_userprofile_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calorie_goal',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='wellnesslog',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('Walking', 'Walking'), ('Jogging', 'Jogging'), ('Running', 'Running'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming'), ('Gym', 'Gym'), ('Yoga', 'Yoga')], max_length=100),
        ),
    ]
