# Generated by Django 5.2.3 on 2025-07-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApp', '0005_userprofile_calorie_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnesslog',
            name='water_intake_ml',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
